### ISSUE TITLE
FastifyError: Schema with id 'Schema' already declared!

### ISSUE THREAD

**Issue by immohanravi** [TomDoesTech/fastify-prisma-rest-api#3]
hi,
First of all, the video is great I have learned a lot, thank you so much.

Looks like there is something has changed in fastify, i have followed your tutorial video everything went great up until I add product.schema to addschema() function in fastify app.ts file. I am getting the below error.

`(node:27437) [FST_MODULE_DEP_FASTIFY-JWT] FastifyWarning.fastify-jwt: fastify-jwt has been deprecated. Use @fastify/jwt@5.0.0 instead.
(Use `node --trace-warnings ...` to show where the warning was created)
FastifyError: Schema with id 'Schema' already declared!
    at Schemas.add (/home/mohan/Programming/fastify/tutorial/node_modules/fastify/lib/schemas.js:33:11)
    at SchemaController.add (/home/mohan/Programming/fastify/tutorial/node_modules/fastify/lib/schema-controller.js:62:30)
    at Object.addSchema (/home/mohan/Programming/fastify/tutorial/node_modules/fastify/fastify.js:606:29)
    at /home/mohan/Programming/fastify/tutorial/src/app.ts:39:16
    at Generator.next (<anonymous>)
    at /home/mohan/Programming/fastify/tutorial/src/app.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/mohan/Programming/fastify/tutorial/src/app.ts:4:12)
    at main (/home/mohan/Programming/fastify/tutorial/src/app.ts:41:12)
    at Object.<anonymous> (/home/mohan/Programming/fastify/tutorial/src/app.ts:56:1)
[ERROR] 21:10:41 FastifyError: Schema with id 'Schema' already declared!
Child got SIGTERM, exiting.`

**Error is because of that id, see below console.log of schema**

![Screenshot_20221020_212101](https://user-images.githubusercontent.com/10009086/196997456-eba6794c-dd2e-4b24-9e08-de68a6b270f6.png)

I have no idea how to solve it, I thought I made some error but the same problem persist even when I clone and run this project. please have a look

**Comment by RomainMarcazzan** [comment]
Same problem here, I tried that in main(), because the problem is that both schemas have the same ID ("Schema") but I still have an error:

  const newUserSchema = userSchemas.map((sc) => {
    return { ...sc, $id: "UserSchemaId" };
  });
  const newPostSchema = postSchemas.map((sc) => {
    return { ...sc, $id: "PostSchemaId" };
  });

  for (const schema of [...newUserSchema, ...newPostSchema]) {
    server.addSchema(schema);
  }

`FastifyError [Error]: Failed building the validation schema for POST: /api/v1/users, due to error can't resolve reference Schema#/properties/registerSchema from id #
    at Boot.<anonymous> (C:\Users\romai\Documents\Project\FBF\backend\node_modules\fastify\lib\route.js:355:21)
    at Object.onceWrapper (node:events:627:28)
    at Boot.emit (node:events:525:35)
    at C:\Users\romai\Documents\Project\FBF\backend\node_modules\avvio\boot.js:160:12
    at C:\Users\romai\Documents\Project\FBF\backend\node_modules\avvio\plugin.js:275:7
    at done (C:\Users\romai\Documents\Project\FBF\backend\node_modules\avvio\plugin.js:200:5)
    at check (C:\Users\romai\Documents\Project\FBF\backend\node_modules\avvio\plugin.js:224:9)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8) {
  code: 'FST_ERR_SCH_VALIDATION_BUILD',
  statusCode: 500
}`

**Comment by RomainMarcazzan** [comment]
You can specify a unique $id for each schemas
`export const { schemas: userSchemas, $ref } = buildJsonSchemas(
  {
    registerSchema,
    registerResponseSchema,
    loginSchema,
    loginResponseSchema,
    getUsersResponseSchema,
  },
  {
    $id: "UserSchema",
  }
);`

`export const { schemas: postSchemas, $ref } = buildJsonSchemas(
  {
    createPostSchema,
    postResponseSchema,
    postsResponseSchema,
  },
  {
    $id: "PostSchema",
  }
);`

I think it's not post but product in the tutorial but it's the same idea

**Comment by cwgabel** [comment]
I too had the same problem. I was keying along with Tom and then halfway through I got the same error.  I suspect it was something I keyed in wrong.  I cloned the repo and everything executed as expected.
